#!/bin/sh

#####################
# ENV
#####################
[ "$ENV_FILE" ]                        || ENV_FILE='./.env'
[ ! -f "$ENV_FILE" ]                   || . "$ENV_FILE"

#####################
# NETWORKING
#####################
[ "$LOCAL_IP" ]                        || LOCAL_IP="$(/sbin/ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p' | head -1)"

#####################
# FILE PATHS
#####################
[ "$DOCKER_COMPOSE" ]                  || DOCKER_COMPOSE='docker-compose.yml'
[ "$GIT_ROOT" ]                        || GIT_ROOT="$(pwd)"

#####################
# CLIENT
#####################
[ "$CLIENT_NAME" ]                     || CLIENT_NAME='overseer_client'
[ "$CLIENT_IMAGE" ]                    || CLIENT_IMAGE='overseer/client'
[ "$CLIENT_TAG" ]                      || CLIENT_TAG='latest'
[ "$CLIENT_PATH" ]                     || CLIENT_PATH="${GIT_ROOT}/client"
[ "$CLIENT_IP" ]                       || CLIENT_IP="${LOCAL_IP}"
[ "$CLIENT_HP" ]                       || CLIENT_HP='4000'
[ "$CLIENT_CP" ]                       || CLIENT_CP='4000'
[ "$CLIENT_PROTOCOL" ]                 || CLIENT_PROTOCOL='http'
[ "$CLIENT_URL" ]                      || CLIENT_URL="${CLIENT_PROTOCOL}://${CLIENT_IP}:${CLIENT_HP}"

######################
# GATEWAY
###################### 
[ "$GATEWAY_NAME" ]                    || GATEWAY_NAME='overseer_gateway'
[ "$GATEWAY_IMAGE" ]                   || GATEWAY_IMAGE='overseer/gateway'
[ "$GATEWAY_TAG" ]                     || GATEWAY_TAG='latest'
[ "$GATEWAY_PATH" ]                    || GATEWAY_PATH="${GIT_ROOT}/gateway"
[ "$GATEWAY_IP" ]                      || GATEWAY_IP="${LOCAL_IP}"
[ "$GATEWAY_HP" ]                      || GATEWAY_HP='41000'
[ "$GATEWAY_CP" ]                      || GATEWAY_CP='8000'
[ "$GATEWAY_PROTOCOL" ]                || GATEWAY_PROTOCOL='http'
[ "$GATEWAY_URL" ]                     || GATEWAY_URL="${GATEWAY_PROTOCOL}://${GATEWAY_IP}:${GATEWAY_HP}"

######################
# DASHBOARD_SERVICE
######################
# Server
[ "$DASHBOARD_SERVICE_NAME" ]          || DASHBOARD_SERVICE_NAME='overseer_dashboard_service'
[ "$DASHBOARD_SERVICE_IMAGE" ]         || DASHBOARD_SERVICE_IMAGE='overseer/dashboard_service'
[ "$DASHBOARD_SERVICE_TAG" ]           || DASHBOARD_SERVICE_TAG='latest'
[ "$DASHBOARD_SERVICE_PATH" ]          || DASHBOARD_SERVICE_PATH="${GIT_ROOT}/dashboard_service"
[ "$DASHBOARD_SERVICE_HP" ]            || DASHBOARD_SERVICE_HP='41010'
[ "$DASHBOARD_SERVICE_CP" ]            || DASHBOARD_SERVICE_CP='8000'
[ "$DASHBOARD_SERVICE_PROTOCOL" ]      || DASHBOARD_SERVICE_PROTOCOL='http'
[ "$DASHBOARD_SERVICE_URL" ]           || DASHBOARD_SERVICE_URL="${DASHBOARD_SERVICE_PROTOCOL}://${DASHBOARD_SERVICE_NAME}:${DASHBOARD_SERVICE_CP}"

# Database
[ "$DASHBOARD_DB_NAME" ]               || DASHBOARD_DB_NAME='overseer_dashboard_db'
[ "$DASHBOARD_DB_IMAGE" ]              || DASHBOARD_DB_IMAGE='mongo'
[ "$DASHBOARD_DB_TAG" ]                || DASHBOARD_DB_TAG='4.0.5'
[ "$DASHBOARD_DB_VOLUME_NAME" ]        || DASHBOARD_DB_VOLUME_NAME='overseer_dashboard_db_volume'
[ "$DASHBOARD_DB_HP" ]                 || DASHBOARD_DB_HP='41011'
[ "$DASHBOARD_DB_CP" ]                 || DASHBOARD_DB_CP='41011'

#####################
# TILE_SERVICE
#####################
# Server
[ "$TILE_SERVICE_NAME" ]               || TILE_SERVICE_NAME='overseer_tile_service'
[ "$TILE_SERVICE_IMAGE" ]              || TILE_SERVICE_IMAGE='overseer/tile_service'
[ "$TILE_SERVICE_TAG" ]                || TILE_SERVICE_TAG='latest'
[ "$TILE_SERVICE_PATH" ]               || TILE_SERVICE_PATH="${GIT_ROOT}/tile_service"
[ "$TILE_SERVICE_HP" ]                 || TILE_SERVICE_HP='41020'
[ "$TILE_SERVICE_CP" ]                 || TILE_SERVICE_CP='8000'
[ "$TILE_SERVICE_PROTOCOL" ]           || TILE_SERVICE_PROTOCOL='http'
[ "$TILE_SERVICE_URL" ]                || TILE_SERVICE_URL="${TILE_SERVICE_PROTOCOL}://${TILE_SERVICE_NAME}:${TILE_SERVICE_CP}"

# Database
[ "$TILE_DB_NAME" ]                    || TILE_DB_NAME='overseer_tile_db'
[ "$TILE_DB_IMAGE" ]                   || TILE_DB_IMAGE='mongo'
[ "$TILE_DB_TAG" ]                     || TILE_DB_TAG='4.0.5'
[ "$TILE_DB_VOLUME_NAME" ]             || TILE_DB_VOLUME_NAME='overseer_tile_db_volume'
[ "$TILE_DB_HP" ]                      || TILE_DB_HP='41021'
[ "$TILE_DB_CP" ]                      || TILE_DB_CP='41021'

######################
# DASHBOARD_SERVICE
######################
# Server
[ "$USER_SERVICE_NAME" ]               || USER_SERVICE_NAME='overseer_user_service'
[ "$USER_SERVICE_IMAGE" ]              || USER_SERVICE_IMAGE='overseer/user_service'
[ "$USER_SERVICE_TAG" ]                || USER_SERVICE_TAG='latest'
[ "$USER_SERVICE_PATH" ]               || USER_SERVICE_PATH="${GIT_ROOT}/user_service"
[ "$USER_SERVICE_HP" ]                 || USER_SERVICE_HP='41030'
[ "$USER_SERVICE_CP" ]                 || USER_SERVICE_CP='8000'
[ "$USER_SERVICE_PROTOCOL" ]           || USER_SERVICE_PROTOCOL='http'
[ "$USER_SERVICE_URL" ]                || USER_SERVICE_URL="${USER_SERVICE_PROTOCOL}://${USER_SERVICE_NAME}:${USER_SERVICE_CP}"

# Database
[ "$USER_DB_NAME" ]                    || USER_DB_NAME='overseer_user_db'
[ "$USER_DB_IMAGE" ]                   || USER_DB_IMAGE='mongo'
[ "$USER_DB_TAG" ]                     || USER_DB_TAG='4.0.5'
[ "$USER_DB_VOLUME_NAME" ]             || USER_DB_VOLUME_NAME='overseer_user_db_volume'
[ "$USER_DB_HP" ]                      || USER_DB_HP='41031'
[ "$USER_DB_CP" ]                      || USER_DB_CP='41031'

######################
# WORKER_SERVICE
######################
# Server
[ "$WORKER_QUEUE_SERVICE_NAME" ]       || WORKER_QUEUE_SERVICE_NAME='overseer_worker_queue_service'
[ "$WORKER_RUNNER_SERVICE_NAME" ]      || WORKER_RUNNER_SERVICE_NAME='overseer_worker_runner_service'
[ "$WORKER_SERVICE_IMAGE" ]            || WORKER_SERVICE_IMAGE='overseer/worker_service'
[ "$WORKER_SERVICE_TAG" ]              || WORKER_SERVICE_TAG='latest'
[ "$WORKER_SERVICE_PATH" ]             || WORKER_SERVICE_PATH="${GIT_ROOT}/worker_service"
[ "$WORKER_QUEUE_SERVICE_HP" ]         || WORKER_QUEUE_SERVICE_HP='41040'
[ "$WORKER_RUNNER_SERVICE_HP" ]        || WORKER_RUNNER_SERVICE_HP='41140'
[ "$WORKER_SERVICE_CP" ]               || WORKER_SERVICE_CP='8000'
[ "$WORKER_SERVICE_PROTOCOL" ]         || WORKER_SERVICE_PROTOCOL='http'
[ "$WORKER_SERVICE_URL" ]              || WORKER_SERVICE_URL="${WORKER_SERVICE_PROTOCOL}://${WORKER_SERVICE_NAME}:${WORKER_SERVICE_CP}"

# Database
[ "$WORKER_DB_NAME" ]                  || WORKER_DB_NAME='overseer_worker_db'
[ "$WORKER_DB_IMAGE" ]                 || WORKER_DB_IMAGE='redis'
[ "$WORKER_DB_TAG" ]                   || WORKER_DB_TAG='5.0-alpine'
[ "$WORKER_DB_VOLUME_NAME" ]           || WORKER_DB_VOLUME_NAME='overseer_worker_db_volume'
[ "$WORKER_DB_HP" ]                    || WORKER_DB_HP='41041'
[ "$WORKER_DB_CP" ]                    || WORKER_DB_CP='6379' # Default redis port

ARGS="$@"

stop_container() {
  docker kill "$1" > /dev/null 2>&1
  docker rm "$1"   > /dev/null 2>&1
  echo "Container '$1' stopped"
}

stop_overseer() {
  stop_container "$CLIENT_NAME"
  stop_container "$GATEWAY_NAME"
  stop_container "$DASHBOARD_SERVICE_NAME"
  stop_container "$DASHBOARD_DB_NAME"
  stop_container "$TILE_SERVICE_NAME"
  stop_container "$TILE_DB_NAME"
  stop_container "$USER_SERVICE_NAME"
  stop_container "$USER_DB_NAME"
  stop_container "$WORKER_QUEUE_SERVICE_NAME"
  stop_container "$WORKER_RUNNER_SERVICE_NAME"
  stop_container "$WORKER_DB_NAME"
}

setup() {
  stop_overseer
  docker volume create "$DASHBOARD_DB_VOLUME_NAME"
  docker volume create "$TILE_DB_VOLUME_NAME"
  docker volume create "$USER_DB_VOLUME_NAME"
  docker volume create "$WORKER_DB_VOLUME_NAME"
}

create_compose_file() {
cat <<EOT > $DOCKER_COMPOSE
version: "3"

services:
  ${CLIENT_NAME}:
    container_name: ${CLIENT_NAME}
    image: ${CLIENT_IMAGE}:${CLIENT_TAG}
    build:
      context: ${CLIENT_PATH}
      dockerfile: ${CLIENT_PATH}/docker/Dockerfile
    ports:
      - '${CLIENT_HP}:${CLIENT_CP}'
    environment:
      - PORT=${CLIENT_CP}
      - API_URL=http://${GATEWAY_IP}:${GATEWAY_HP}/
    volumes:
      - ${CLIENT_PATH}/src:/data/src
      - ${CLIENT_PATH}/test:/data/test
      - ${CLIENT_PATH}/build:/data/build
      - ${CLIENT_PATH}/config:/data/config

  ${GATEWAY_NAME}:
    container_name: ${GATEWAY_NAME}
    image: ${GATEWAY_IMAGE}:${GATEWAY_TAG}
    build:
      context: ${GATEWAY_PATH}
      dockerfile: ${GATEWAY_PATH}/docker/Dockerfile
    ports:
      - '${GATEWAY_HP}:${GATEWAY_CP}'
    environment:
      - PORT=${GATEWAY_CP}
      - SERVICE_URL=${GATEWAY_URL}
      - CLIENT_URL=${CLIENT_URL}
      - DASHBOARD_SERVICE_URL=${DASHBOARD_SERVICE_URL}
      - TILE_SERVICE_URL=${TILE_SERVICE_URL}
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      - WORKER_SERVICE_URL=${WORKER_SERVICE_URL}
    volumes:
      - ${GATEWAY_PATH}/src:/data/src
    command:
      - ./node_modules/nodemon/bin/nodemon.js
      - "--experimental-modules"
      - "--legacy-watch"
      - "--inspect=0.0.0.0"
      - "./src/app.mjs" 
    
  ${DASHBOARD_SERVICE_NAME}:
    container_name: ${DASHBOARD_SERVICE_NAME}
    image: ${DASHBOARD_SERVICE_IMAGE}:${DASHBOARD_SERVICE_TAG}
    build:
      context: ${DASHBOARD_SERVICE_PATH}
      dockerfile: ${DASHBOARD_SERVICE_PATH}/docker/Dockerfile
    ports:
      - '${DASHBOARD_SERVICE_HP}:${DASHBOARD_SERVICE_CP}'
    environment:
      - PORT=${DASHBOARD_SERVICE_CP}
      - SERVICE_URL=${DASHBOARD_SERVICE_URL}
      - DATABASE_URL=${DASHBOARD_DB_NAME}:${DASHBOARD_DB_HP}
    depends_on: 
      - ${DASHBOARD_DB_NAME}
    volumes:
      - ${DASHBOARD_SERVICE_PATH}/src:/data/src
    command:
      - ./node_modules/nodemon/bin/nodemon.js
      - "--experimental-modules"
      - "--legacy-watch"
      - "--inspect=0.0.0.0"
      - "./src/app.mjs" 

  ${DASHBOARD_DB_NAME}:
    container_name: ${DASHBOARD_DB_NAME}
    image: ${DASHBOARD_DB_IMAGE}:${DASHBOARD_DB_TAG}
    ports:
      - '${DASHBOARD_DB_HP}:${DASHBOARD_DB_CP}'
    volumes:
      - ${DASHBOARD_DB_VOLUME_NAME}:/data/db
    command: mongod --port ${DASHBOARD_DB_CP}
    
  ${TILE_SERVICE_NAME}:
    container_name: ${TILE_SERVICE_NAME}
    image: ${TILE_SERVICE_IMAGE}:${TILE_SERVICE_TAG}
    build:
      context: ${TILE_SERVICE_PATH}
      dockerfile: ${TILE_SERVICE_PATH}/docker/Dockerfile
    ports:
      - '${TILE_SERVICE_HP}:${TILE_SERVICE_CP}'
    environment:
      - PORT=${TILE_SERVICE_CP}
      - SERVICE_URL=${TILE_SERVICE_URL}
      - DATABASE_URL=${TILE_DB_NAME}:${TILE_DB_HP}
    depends_on: 
      - ${TILE_DB_NAME}
    volumes:
      - ${TILE_SERVICE_PATH}/src:/data/src
    command:
      - ./node_modules/nodemon/bin/nodemon.js
      - "--experimental-modules"
      - "--legacy-watch"
      - "--inspect=0.0.0.0"
      - "./src/app.mjs" 

  ${TILE_DB_NAME}:
    container_name: ${TILE_DB_NAME}
    image: ${TILE_DB_IMAGE}:${TILE_DB_TAG}
    ports:
      - '${TILE_DB_HP}:${TILE_DB_CP}'
    volumes:
      - ${TILE_DB_VOLUME_NAME}:/data/db
    command: mongod --port ${TILE_DB_CP}

  ${USER_SERVICE_NAME}:
    container_name: ${USER_SERVICE_NAME}
    image: ${USER_SERVICE_IMAGE}:${USER_SERVICE_TAG}
    build:
      context: ${USER_SERVICE_PATH}
      dockerfile: ${USER_SERVICE_PATH}/docker/Dockerfile
    ports:
      - '${USER_SERVICE_HP}:${USER_SERVICE_CP}'
    environment:
      - PORT=${USER_SERVICE_CP}
      - SERVICE_URL=${USER_SERVICE_URL}
      - DATABASE_URL=${USER_DB_NAME}:${USER_DB_HP}
    depends_on: 
      - ${USER_DB_NAME}
    volumes:
      - ${USER_SERVICE_PATH}/src:/data/src
    command:
      - ./node_modules/nodemon/bin/nodemon.js
      - "--experimental-modules"
      - "--legacy-watch"
      - "--inspect=0.0.0.0"
      - "./src/app.mjs" 

  ${USER_DB_NAME}:
    container_name: ${USER_DB_NAME}
    image: ${TILE_DB_IMAGE}:${USER_DB_TAG}
    ports:
      - '${USER_DB_HP}:${USER_DB_CP}'
    volumes:
      - ${USER_DB_VOLUME_NAME}:/data/db
    command: mongod --port ${USER_DB_CP}

  ${WORKER_QUEUE_SERVICE_NAME}:
    container_name: ${WORKER_QUEUE_SERVICE_NAME}
    image: ${WORKER_SERVICE_IMAGE}:${WORKER_SERVICE_TAG}
    build:
      context: ${WORKER_SERVICE_PATH}
      dockerfile: ${WORKER_SERVICE_PATH}/docker/Dockerfile
    ports:
      - '${WORKER_QUEUE_SERVICE_HP}:${WORKER_SERVICE_CP}'
    environment:
      - PORT=${WORKER_SERVICE_CP}
      - SERVICE_URL=${WORKER_SERVICE_URL}
      - DATABASE_NAME=${WORKER_DB_NAME}
      - DATABASE_PORT=${WORKER_DB_HP}
    depends_on: 
      - ${WORKER_DB_NAME}
    volumes:
      - ${WORKER_SERVICE_PATH}/src:/data/src
    command:
      - ./node_modules/nodemon/bin/nodemon.js
      - "--experimental-modules"
      - "--legacy-watch"
      - "--inspect=0.0.0.0"
      - "./src/app.mjs" 

  ${WORKER_RUNNER_SERVICE_NAME}:
    container_name: ${WORKER_RUNNER_SERVICE_NAME}
    image: ${WORKER_SERVICE_IMAGE}:${WORKER_SERVICE_TAG}
    build:
      context: ${WORKER_SERVICE_PATH}
      dockerfile: ${WORKER_SERVICE_PATH}/docker/Dockerfile
    ports:
      - '${WORKER_RUNNER_SERVICE_HP}:${WORKER_SERVICE_CP}'
    environment:
      - PORT=${WORKER_SERVICE_CP}
      - SERVICE_URL=${WORKER_SERVICE_URL}
      - DATABASE_NAME=${WORKER_DB_NAME}
      - DATABASE_PORT=${WORKER_DB_HP}
    depends_on: 
      - ${WORKER_DB_NAME}
    volumes:
      - ${WORKER_SERVICE_PATH}/src:/data/src
    command:
      - ./node_modules/nodemon/bin/nodemon.js
      - "--experimental-modules"
      - "--legacy-watch"
      - "--inspect=0.0.0.0"
      - "./src/worker.mjs" 

  ${WORKER_DB_NAME}:
    container_name: ${WORKER_DB_NAME}
    image: ${WORKER_DB_IMAGE}:${WORKER_DB_TAG}
    ports:
      - '${WORKER_DB_HP}:${WORKER_DB_CP}'
    volumes:
      - ${WORKER_DB_VOLUME_NAME}:/data/db

volumes:
  ${DASHBOARD_DB_VOLUME_NAME}:
    external: true
  ${TILE_DB_VOLUME_NAME}:
    external: true
  ${USER_DB_VOLUME_NAME}:
    external: true
  ${WORKER_DB_VOLUME_NAME}:
    external: true
EOT
}

build_overseer() {
  docker-compose build
}

start_overseer() {
  setup
  docker-compose up -d
  docker-compose logs -f
}

dev_overseer() {
  setup
  docker-compose up -d
  docker-compose logs -f
}

reset_overseer() {
  stop_overseer
  clear_node_modules
  delete_database
}

delete_database() {
  docker volume rm "$DASHBOARD_DB_VOLUME_NAME" > /dev/null 2>&1 && echo "Removed $DASHBOARD_DB_VOLUME_NAME"
  docker volume rm "$TILE_DB_VOLUME_NAME"      > /dev/null 2>&1 && echo "Removed $TILE_DB_VOLUME_NAME"
  docker volume rm "$USER_DB_VOLUME_NAME"      > /dev/null 2>&1 && echo "Removed $USER_DB_VOLUME_NAME"
  docker volume rm "$WORKER_DB_VOLUME_NAME"    > /dev/null 2>&1 && echo "Removed $WORKER_DB_VOLUME_NAME"
}

create_compose_file
if [ "${ARGS#*build}" != "$ARGS" ]; then
  build_overseer
elif [ "${ARGS#*start}" != "$ARGS" ]; then
  start_overseer
elif [ "${ARGS#*stop}" != "$ARGS" ]; then
  stop_overseer
elif [ "${ARGS#*dev}" != "$ARGS" ]; then
  dev_overseer
elif [ "${ARGS#*reset}" != "$ARGS" ]; then
  reset_overseer
elif [ "${ARGS#*reset}" != "$ARGS" ]; then
  stop_overseer
  delete_database
fi
