version: '3'

services:
  overseer_db:
    image: 'postgres'
    container_name: 'overseer_db'
    restart: 'always'
    environment:
      POSTGRES_DB: 'overseer_db'
      POSTGRES_USERNAME: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - 'overseer_db:/var/lib/postgresql/data'

  overseer:
    image: ${OVERSEER_IMAGE}
    container_name: 'overseer'
    restart: 'always'
    depends_on:
      - 'overseer_db'
    environment:
      PAGER: 'busybox more'
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: 'overseer_db'
      RAILS_ENV: "${RAILS_ENV}"
    ports:
      - "${EXTERNAL_PORT}:3000"
    volumes:
      - '../:/home/docker/overseer'

volumes:
  overseer_db:
    external: true