default: &default
  adapter: postgresql
  encoding: unicode
  host: api-monitor_db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: api-monitor_development


test:
  <<: *default
  database: api-monitor_test