default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  username:  <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %> 
  pool: 5

development:
  <<: *default
  database: overseer_development

test:
  <<: *default
  database: overseer_test

production:
  <<: *default
  database: overseer_production