default: &default
  adapter: postgresql
  encoding: unicode
  host: overseer_db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: overseer_development


test:
  <<: *default
  database: overseer_test